### PR TITLE
build: use zig 0.13.0

### PR DESCRIPTION
**Pull request by hendriknielaender**
- [x] update README.md
- [x] github action
- [x] use `std.process.Child`
- [x] build.zig lazyPath
- [ ] ~~new std.Progress api~~ 
- [x] added zon file

Closes https://github.com/hendriknielaender/zBench/issues/84

### CODE REVIEW

**Comment by ivanstepanovftw** [comment]
And migration:
```zig
exe.addAnonymousModule("zbench", .{
  .source_file = .{ .path = "libs/zbench/zbench.zig" },
});
```
V
```zig
exe.root_module.addAnonymousImport("zbench", .{
  .root_source_file = b.path("libs/zbench/zbench.zig"),
});
```

**Comment by hendriknielaender** [comment]
@bens @FObersteiner does somebody have a smart idea to integrate the new progress api?

**Comment by FObersteiner** [comment]
> @bens @FObersteiner does somebody have a smart idea to integrate the new progress api?

unfortunately I don't. Personally I haven't found a good use for this API, while at the same time it seems like a considerable amount of work to get into it. Andrew Kelley even wrote a [blog post](https://andrewkelley.me/post/zig-new-cli-progress-bar-explained.html) about it, but I wouldn't call this "user-facing documentation", however *thread-safe, lock-free, and avoid contention* sounds promising.

**Comment by hendriknielaender** [comment]
@FObersteiner I removed the old `std.Progress`, and leave the new progress api out of scope for this PR.

For the failing macOS platform test, I will have a look couldn't re-produce it on my machine.

**Comment by FObersteiner** [comment]
> @FObersteiner I removed the old `std.Progress`, and leave the new progress api out of scope for this PR.
> 
> For the failing macOS platform test, I will have a look couldn't re-produce it on my machine.

added a zon file for convenient usage of the library in other projects. 

doesn't fix the CI error ofc ^^ looks like it's coming from the platform info example.

**Comment by hendriknielaender** [comment]
@FObersteiner increased fixed buffer alloc to from 4096 to 8192 fixed the issue.
Maybe there is a smarter way to determine the fixed alloc for each platform.

**Comment by FObersteiner** [comment]
> @FObersteiner increased fixed buffer alloc to from 4096 to 8192 fixed the issue. Maybe there is a smarter way to determine the fixed alloc for each platform.

right... nevertheless, even only 4k seems like overkill to parse an int

**Comment by hendriknielaender** [comment]
> > @FObersteiner increased fixed buffer alloc to from 4096 to 8192 fixed the issue. Maybe there is a smarter way to determine the fixed alloc for each platform.
> 
> right... nevertheless, even only 4k seems like overkill to parse an int

You are right, i created an issue to fix this even 4096 like you mentioned seems to overkill.
https://github.com/hendriknielaender/zBench/issues/88

**Pull request merged**
